### ISSUE TITLE
这个库现在还能用不？

### ISSUE THREAD

**Issue by sunface** [tukdesk/bleve-sego-tokenizer#1]
如题，希望作者有时间能解惑下

**Comment by sunface** [comment]
example跑了下，跑错了，main.go:39: no analyzer with name or type 'custom' registered

**Comment by dtynn** [comment]
这个库已经很久没有维护, 可能 bleve 的 api 有改动
暂时没有精力重新维护这个库, 建议按照 bleve 的 tokenizer 和 analyzer 接口自行封装
